export { default as Home } from './home'
export { default as NullPage } from './null/nullPage'
export { default as Product } from './products'
export { default as Info } from './info'
export { default as ProductSingular } from './productSingular'
export { default as AdminAddOrEdit } from './updateAdd'
export { default as Edit } from './edit'
